<<<<<<< HEAD
<<<<<<< HEAD
# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'volunteer_app',
# ]

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / "db.sqlite3",
#     }
# }
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'volunteer_app/templates'],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]
import os
from pathlib import Path

# Шлях до кореневої директорії проєкту
BASE_DIR = Path(__file__).resolve().parent.parent

# Безпека
SECRET_KEY = 'your-secret-key-here'
DEBUG = True  # Змінити на False у продакшені
ALLOWED_HOSTS = []  # Додай домени, якщо потрібно

# Встановлені додатки
=======
=======
>>>>>>> 06648135a6a47c01fe23792866272ebd11063a6a
"""
Django settings for volunteer_project project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9fb$#7jkjfzg$o!bl=4+rvahk*q5rnpo605a61+9s(s%+off@9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

<<<<<<< HEAD
>>>>>>> 06648135a6a47c01fe23792866272ebd11063a6a
=======
>>>>>>> 06648135a6a47c01fe23792866272ebd11063a6a
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
<<<<<<< HEAD
    'volunteer_app',  # Твій додаток
]

# Середні сервіси
=======
    'volunteer_app',
]

>>>>>>> 06648135a6a47c01fe23792866272ebd11063a6a
=======
    'volunteer_app',
]

>>>>>>> 06648135a6a47c01fe23792866272ebd11063a6a
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

<<<<<<< HEAD
<<<<<<< HEAD
# URL конфігурація
ROOT_URLCONF = 'volunteer_project.urls'

# Налаштування шаблонів
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'volunteer_app/templates'],  # Шлях до шаблонів
=======
=======
>>>>>>> 06648135a6a47c01fe23792866272ebd11063a6a
ROOT_URLCONF = 'volunteer_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
<<<<<<< HEAD
>>>>>>> 06648135a6a47c01fe23792866272ebd11063a6a
=======
>>>>>>> 06648135a6a47c01fe23792866272ebd11063a6a
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

<<<<<<< HEAD
<<<<<<< HEAD
# WSGI для розгортання
WSGI_APPLICATION = 'volunteer_project.wsgi.application'

# База даних (SQLite)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / "db.sqlite3",
    }
}

# Налаштування аутентифікації
=======
=======
>>>>>>> 06648135a6a47c01fe23792866272ebd11063a6a

WSGI_APPLICATION = 'volunteer_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

<<<<<<< HEAD
>>>>>>> 06648135a6a47c01fe23792866272ebd11063a6a
=======
>>>>>>> 06648135a6a47c01fe23792866272ebd11063a6a
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

<<<<<<< HEAD
<<<<<<< HEAD
# Мови та часовий пояс
LANGUAGE_CODE = 'uk'
TIME_ZONE = 'Europe/Kyiv'
USE_I18N = True
USE_TZ = True

# Статичні файли
STATIC_URL = '/static/'

# Куди збирати файли при collectstatic
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Додаткові папки зі статикою
STATICFILES_DIRS = [
    BASE_DIR / 'volunteer_app/static/css',
]

# Медіафайли (якщо використовуєш завантаження зображень)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Тип поля первинного ключа за замовчуванням
=======
=======
>>>>>>> 06648135a6a47c01fe23792866272ebd11063a6a

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

<<<<<<< HEAD
>>>>>>> 06648135a6a47c01fe23792866272ebd11063a6a
=======
>>>>>>> 06648135a6a47c01fe23792866272ebd11063a6a
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
