# Generated by Django 5.1.7 on 2025-03-27 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_app', '0003_remove_request_created_at_request_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='request',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='request_photos/'),
        ),
    ]
