# Generated by Django 5.1.7 on 2025-03-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_app', '0005_alter_request_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='request',
            name='location',
        ),
        migrations.RemoveField(
            model_name='request',
            name='title',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
        migrations.AddField(
            model_name='request',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('accepted', 'Прийнятий'), ('rejected', 'Відхилений')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='urgency',
            field=models.CharField(choices=[('висока', 'Висока'), ('середня', 'Середня'), ('низька', 'Низька')], max_length=50),
        ),
    ]
